// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9V-igkP5hl-x23RroviksN5cMstbffLU',
    appId: '1:748561237711:web:34e94d2b0029ed429719ba',
    messagingSenderId: '748561237711',
    projectId: 'pay-reminder-5fcd9',
    authDomain: 'pay-reminder-5fcd9.firebaseapp.com',
    storageBucket: 'pay-reminder-5fcd9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vMwUYoQBadZJwzWC6ZEP8VuwLSq5zO0',
    appId: '1:748561237711:android:2a7ebb9fc01a30049719ba',
    messagingSenderId: '748561237711',
    projectId: 'pay-reminder-5fcd9',
    storageBucket: 'pay-reminder-5fcd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lcIWGj_iUrLU0j9qX17TO72rvyG9MyI',
    appId: '1:748561237711:ios:b6f5548c6dc865169719ba',
    messagingSenderId: '748561237711',
    projectId: 'pay-reminder-5fcd9',
    storageBucket: 'pay-reminder-5fcd9.firebasestorage.app',
    iosBundleId: 'dev.donmanuel.payReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lcIWGj_iUrLU0j9qX17TO72rvyG9MyI',
    appId: '1:748561237711:ios:b6f5548c6dc865169719ba',
    messagingSenderId: '748561237711',
    projectId: 'pay-reminder-5fcd9',
    storageBucket: 'pay-reminder-5fcd9.firebasestorage.app',
    iosBundleId: 'dev.donmanuel.payReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9V-igkP5hl-x23RroviksN5cMstbffLU',
    appId: '1:748561237711:web:5b48beda7d16d5e49719ba',
    messagingSenderId: '748561237711',
    projectId: 'pay-reminder-5fcd9',
    authDomain: 'pay-reminder-5fcd9.firebaseapp.com',
    storageBucket: 'pay-reminder-5fcd9.firebasestorage.app',
  );
}
